#!/bin/bash

# Setup script for Mem0 with PostgreSQL pgvector
# This script helps configure environment variables for Mem0 to use PostgreSQL

echo "=== Mem0 PostgreSQL Setup ==="
echo ""
echo "This script will help you configure Mem0 to use PostgreSQL with pgvector"
echo "instead of the default SQLite storage."
echo ""

# Create backup of current .env if it exists
if [ -f "../.env" ]; then
    cp ../.env ../.env.backup.$(date +%Y%m%d_%H%M%S)
    echo "✓ Created backup of .env file"
fi

echo ""
echo "Add the following environment variables to your backend/.env file:"
echo ""
echo "# Mem0 Configuration"
echo "MEM0_ENABLED=true"
echo "MEM0_PROVIDER=pgvector"
echo ""
echo "# If you have specific PostgreSQL settings different from the main database,"
echo "# you can override them here (optional):"
echo "# POSTGRES_HOST=localhost"
echo "# POSTGRES_PORT=5432"
echo "# POSTGRES_USER=postgres"
echo "# POSTGRES_PASSWORD=your_password"
echo "# POSTGRES_DB=chatsg"
echo ""
echo "# Or use a single DATABASE_URL if preferred:"
echo "# DATABASE_URL=postgresql://user:password@localhost:5432/chatsg"
echo ""
echo "# Optional: Neo4j for graph store (relationship tracking)"
echo "# MEM0_GRAPH_ENABLED=true"
echo "# NEO4J_URL=neo4j://localhost:7687"
echo "# NEO4J_USERNAME=neo4j"
echo "# NEO4J_PASSWORD=your_neo4j_password"
echo ""
echo "=== Next Steps ==="
echo ""
echo "1. Add the above variables to your backend/.env file"
echo ""
echo "2. Run the database migration to create Mem0 tables:"
echo "   cd backend/src/database"
echo "   node run-migration.js 002_create_mem0_tables.sql"
echo ""
echo "3. Restart your backend server to apply changes"
echo ""
echo "4. Test the integration:"
echo "   cd backend/tests/memory"
echo "   node test-mem0-pgvector.js"
echo ""
echo "5. After verification, you can remove old SQLite files:"
echo "   rm backend/memory.db"
echo "   rm backend/vector_store.db"
echo "   rm backend/data/sessions/memory.db"
echo ""
echo "=== Notes ==="
echo "- The pgvector extension will be automatically installed if not present"
echo "- All memories will be isolated by user ID for security"
echo "- The system will fall back to SQLite if pgvector is not available"
echo ""